### ISSUE TITLE
Is it possible to create one for Dreamcast?

### ISSUE THREAD

**Issue by Luks-18** [kapdap/re-cvx-doorskip#1]
I wanted to play the DC version too with Door Skip, do you think it's possible?

**Comment by boomstick1981** [comment]
My thoughts exactly (even though I use the emulated versions), especially for speed running! Not only for the original version, but also for the complete version that was released only in Japan.

**Comment by kapdap** [comment]
A Dreamcast version is possible but it was difficult as the reversing/debugging tools for Dreamcast games aren't as good as other consoles so I gave up on it.

Will keep this open in case someone else wants to take a crack at the Dreamcast release.

**Comment by rnoh96** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

0xBadMad, @C4T4, @xoxander, @furkandoganay0, @mayckonx, @emretepedev, @andrewerb, @suolike, @khadgachy07, @aakansh9, @ofisyelmaik, @louismbenedict, @RyanCloud9527, @Market2199897, @the-real-astro, @wideinch, @SamaanBrainstorms, @jimtje, @toshiakitakase, @whiteath

**Comment by kapdap** [comment]
It's. Finally. Here.

https://github.com/kapdap/re-cvx-patches/blob/master/doorskip/DC.md
