### ISSUE TITLE
Possible help?

### ISSUE THREAD

**Issue by duig0** [kapdap/re-cvx-doorskip#2]
Hi

I am trying to create a first person VR mod using dolphin VR.

https://youtu.be/3GdQ_jKDWMo

Whenever you get attacked an animation plays which hijacks the camera

I wonder would you be able to point me in the right direction to find how to disable that animation?

Many thanks in advance

**Comment by kapdap** [comment]
hi, I checked out your CVX videos, I basically ran into all the same issues with FPS mode that you did (missing textures, camera changed when attacked, game sometimes locking when switching between Clair/Steve etc). So I don't think I can offer you any extra help sorry.

Nice work on the mod :smiley:

**Comment by duig0** [comment]
Thank you so much for the reply

Yeah, it's a real head scratcher 😂

The door skip is great by the way, makes everythng just flow better
