### ISSUE TITLE
Resident Evil CVX Doorskip not work on RPCS3

### ISSUE THREAD

**Issue by ketaro121** [kapdap/re-cvx-doorskip#3]
I have tried both the US and EU Versions. Patch doorskip it doesn't work..
But if it's a Japanese version, it can be used normally.

RPCS3 0.0.32-16574
NPUB30467 (PSN) - not working doorskip
NPEB00553 (PSN) - not working doorskip
NPJB00135 (PSN) - working doorskip

**Comment by kapdap** [comment]
hi, could you provide the PPU hash for the releases that arn't working.
They are displayed in the console log.

![image](https://github.com/kapdap/re-cvx-patches/assets/30880441/1c9fb206-9fa6-4710-967e-c21996bd0ef1)
